Prevent usage of a lockfile for the fresh project directory
We only have the additional pair of server/deno.json and server/deno.lock
because fresh currently requires a deno.json in its project root.
Get rid of the lockfile, which only causes issues when Deno is run under
Linux and Windows:

> error: The source code is invalid, as it does not match the expected hash in the lock file.
>   Specifier: https://esm.sh/*preact-render-to-string@5.2.6
>   Lock file: src/server/deno.lock