fix: Catch simultaneous sync and async errors from different providers
- ProviderError thrown in sync ReleaseLookup constructor: Invalid URL/ID
- Any error thrown during the async stages of a release lookup

Both kinds of errors are handled as expected on their own (even if there
are errors from multiple providers), but a combination of a sync error
and an async error was able to crash the whole server app.

Example: Deezer substitutes a release AND an invalid iTunes ID was given

GET /release?deezer=550027882&itunes=1721471900%C2%AEion%3DKR
> error: Uncaught (in promise) ProviderError: API returned https://www.deezer.com/album/907615612 instead of the requested https://www.deezer.com/album/550027882

This scenario is very rare because invalid URLs/IDs are usually only
specified by beginner users or bad bots which are unlikely to trigger a
valid but failing provider lookup at the same time.